language: node_js
node_js:
    - "6.1"
install:
  - npm install
script:
  - npm run compile
  - npm run phantomTest
  - npm test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - sqlite3
